### PR TITLE
feat: add dragOverlayBg variable

### PR DESCRIPTION
**Pull request by SevenOutman**
The `dragOverlayBg` variable stands for the background color when a page on the PageList is being dragged. The chosen color is "white" and "black" with some alpha value.

Related to https://github.com/toeverything/AFFiNE/pull/2216.

### CODE REVIEW

**Comment by hwangdev97** [comment]
Can you provide a UI screenshot of using the color that doesn't exist in our design system? This would be helpful for us to determine whether we need to add this color. 

thx.

**Comment by SevenOutman** [comment]
> Can you provide a UI screenshot of using the color that doesn't exist in our design system? This would be helpful for us to determine whether we need to add this color.
> 
> thx.

Sure. I updated the color value a bit and demonstrated it in the screencast below. Note the background color and shadow effect of the dragged overlay.

https://github.com/toeverything/design/assets/8225666/0bfa8f78-fd53-400d-bfd7-cada06ee6266

**Comment by hwangdev97** [comment]
That's cool. However, our new sidebar design is currently in progress. I'm afraid this color may not be suitable for the Electron sidebar with the blur effect. 

So I think we can use the existing black10 as a substitute.

**Comment by SevenOutman** [comment]
> That's cool. However, our new sidebar design is currently in progress. I'm afraid this color may not be suitable for the Electron sidebar with the blur effect.

That's OK. BTW, would it be possible to give me some hint what's the new sidebar going to look like?

> So I think we can use the existing black10 as a substitute.

Does `black10` apply to both light/dark themes? Or do you think we still need a dedicated new variable that references white/black color under light/dark theme accordingly?

**Comment by hwangdev97** [comment]
the new sidebar:
shot-2023-05-11-19 31 08@2x

and the with `black10`, on dark mode and light mode:

client app:

shot-2023-05-11-19 35 01@2x

web demo app:

shot-2023-05-11-19 32 31@2x

I think that's okay for both light/dark themes 

* In the web and dark mode version, the color may not look great, but we will make a note of the issues related to dark mode and provide a unified fix through issue tracking. Therefore, I think it's okay to use `black10`.

**Comment by SevenOutman** [comment]
> the new sidebar: 
> 
> and the with `black10`, on dark mode and light mode:
> 
> client app:
> 
> web demo app:
> 
> I think that's okay for both light/dark themes

It looks stunning 🤩! How may I get my hands on the new sidebar? Is is already available in the latest codebase?

> * In the web and dark mode version, the color may not look great, but we will make a note of the issues related to dark mode and provide a unified fix through issue tracking. Therefore, I think it's okay to use `black10`.

That makes sense. Then what about the shadow? Is there a existing variable for shadow that fits the floating drag overlay on both light/dark themes?

**Comment by pengx17** [comment]
> It looks stunning 🤩! How may I get my hands on the new sidebar? Is is already available in the latest codebase?

It has been done and merged in the master branch. You can take a look :D

**Comment by SevenOutman** [comment]
Looks like this change is no longer needed with the latest sidebar design. I'm closing this PR.

**Pull request closed without merging**
